"""variant FK added to images

Revision ID: 73eaae525d99
Revises: 54ce031c4b0a
Create Date: 2026-08-21 01:05:34.035014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '73eaae525d99'
down_revision: Union[str, Sequence[str], None] = '54ce031c4b0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_cart_product_variant', 'cart_items', ['cart_id', 'product_id', 'variant_id'], unique=True, postgresql_nulls_not_distinct=True)
    op.drop_constraint(op.f('cart_items_variant_id_fkey'), 'cart_items', type_='foreignkey')
    op.create_foreign_key(None, 'cart_items', 'product_variants', ['variant_id'], ['id'])
    op.alter_column('order_shipping_addresses', 'shipping_method',
               existing_type=postgresql.ENUM('STANDARD', 'EXPRESS', name='shipping_method'),
               type_=sa.Enum('STANDARD', 'EXPRESS', name='order_shipping_method'),
               postgresql_using='shipping_method::text::order_shipping_method',
               existing_nullable=False)
    op.add_column('product_images', sa.Column('variant_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_product_images_product_id'), table_name='product_images')
    op.create_foreign_key(None, 'product_images', 'product_variants', ['variant_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_product_variants_product_id'), table_name='product_variants')
    op.drop_constraint(op.f('products_category_id_fkey'), 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key(op.f('products_category_id_fkey'), 'products', 'categories', ['category_id'], ['id'])
    op.create_index(op.f('ix_product_variants_product_id'), 'product_variants', ['product_id'], unique=False)
    op.drop_constraint(None, 'product_images', type_='foreignkey')
    op.create_index(op.f('ix_product_images_product_id'), 'product_images', ['product_id'], unique=False)
    op.drop_column('product_images', 'variant_id')
    op.alter_column('order_shipping_addresses', 'shipping_method',
               existing_type=sa.Enum('STANDARD', 'EXPRESS', name='order_shipping_method'),
               type_=postgresql.ENUM('STANDARD', 'EXPRESS', name='shipping_method'),
               postgresql_using='shipping_method::text::shipping_method',
               existing_nullable=False)

    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.create_foreign_key(op.f('cart_items_variant_id_fkey'), 'cart_items', 'product_variants', ['variant_id'], ['id'], ondelete='CASCADE')
    op.drop_index('uq_cart_product_variant', table_name='cart_items', postgresql_nulls_not_distinct=True)
    # ### end Alembic commands ###
